apiVersion: v1
kind: ConfigMap
metadata:
  name: beingmomin-config
  namespace: beingmomin
data:
  PORT: "3000"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "7d"
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: "beingmomin-uploads"
